### ISSUE TITLE
Where can we download it or what can we do use it？

### ISSUE THREAD

**Issue by scris** [Ambicour/Codeic#1]
Hi Aaron Robert I am Dominic Qiu and I am “e4361” in Baidu Tieba.I found that you hid yourself in QQ.
I don't know something about it bu. what does Codeic means?how to make one like this or where did you go?

**Comment by scris** [comment]
@RobertIndie Where did you go ？ Are you still having fun？

**Comment by scris** [comment]
@RobertIndie Where did you go ？ Are you still having fun？

**Comment by RobertIndie** [comment]
我在Github，Codeic还在开发，6月30日会发布。
